// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxDnA3B0v7Wyvim7QjITrr2QgrPAzjGpo',
    appId: '1:248829825694:web:f465c8dbad865decf9a18f',
    messagingSenderId: '248829825694',
    projectId: 'canteen-e3751',
    authDomain: 'canteen-e3751.firebaseapp.com',
    storageBucket: 'canteen-e3751.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNTCFXEY2qPXI_DaVVUdfbB7XQPddMle0',
    appId: '1:248829825694:android:ee42c7181f4e524df9a18f',
    messagingSenderId: '248829825694',
    projectId: 'canteen-e3751',
    storageBucket: 'canteen-e3751.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdnG8sbnPKCwYhDoDYS-bsCe4h6rs13o',
    appId: '1:248829825694:ios:e785eec8a6431824f9a18f',
    messagingSenderId: '248829825694',
    projectId: 'canteen-e3751',
    storageBucket: 'canteen-e3751.appspot.com',
    iosClientId: '248829825694-6316qbed6bd1c34qqmt9p72qulq9md59.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteen2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdnG8sbnPKCwYhDoDYS-bsCe4h6rs13o',
    appId: '1:248829825694:ios:e785eec8a6431824f9a18f',
    messagingSenderId: '248829825694',
    projectId: 'canteen-e3751',
    storageBucket: 'canteen-e3751.appspot.com',
    iosClientId: '248829825694-6316qbed6bd1c34qqmt9p72qulq9md59.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteen2',
  );
}
